[package]
name = "reporter"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.4"
reqwest = { version = "0.11.3", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
log = "0.4.14"
env_logger = "0.9.0"
chrono = "0.4"